version: '0.1.{build}'

clone_depth: 10

environment:
    GitEmail: ci@appveyor.com
    GitAuthor: ci
    GitUsername: mminns
    GitPassword: 
      secure: /GXo1m4yXO8eIbjXBMBOVkC5d05AvG0/+03CmoHZBlsoPp3mnSwDXKLA6CpKNAs3
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

skip_tags: true

skip_commits:
  author: ci

configuration:
  - Release

image: Visual Studio 2017

before_build:
  - dotnet restore

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

build_script:
  - ps: |
      dotnet build -c release "Itofinity.Bitbucket.Rest.sln"
      dotnet pack -c release  -p:PackageVersion=$env:APPVEYOR_BUILD_VERSION

after_build:
  - cmd: .\utils\publish.cmd

artifacts:
  - path: '**\*$(APPVEYOR_BUILD_VERSION).nupkg'
  - path: '.\src\Itofinity.Bitbucket.Cli\bin\$(configuration)\netcoreapp2.1\win-x64\publish'
    name: bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-win-x64
    type: zip
  - path: '.\src\Itofinity.Bitbucket.Cli\bin\$(configuration)\netcoreapp2.1\linux-x64\publish'
    name: bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-linux-x64
    type: zip
  - path: '.\src\Itofinity.Bitbucket.Cli\bin\$(configuration)\netcoreapp2.1\osx-x64\publish'
    name: bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-osx-x64
    type: zip


cache:
  - packages -> **\packages.config

matrix:
  fast_finish: true

on_success:
  - ps : .\appveyor-tag-repository.ps1

deploy:
  - provider: GitHub
    release: bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)
    description: 'Bitbucket Cli Release'
    auth_token:
      secure: /GXo1m4yXO8eIbjXBMBOVkC5d05AvG0/+03CmoHZBlsoPp3mnSwDXKLA6CpKNAs3 # your encrypted token from GitHub
    artifact: /.*\.nupkg/ , bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-win-x64, bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-linux-x64, bbc-cli-v$(APPVEYOR_BUILD_VERSION)-$(configuration)-osx-x64
    draft: false
    prerelease: FALSE
    on:
      branch: master                 # release from master branch only
  - provider: NuGet
    api_key:
      secure: Fe8DovER/ifKSdkuY/3mRvX1nf+ZCtnJhw0i0C8LEdrdndFZO9sMsp3zMlK+cTql
    skip_symbols: false
    artifact: /.*\.nupkg/

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))