/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Bitbucket.Rest.Model
{
    /// <summary>
    /// IssueChangeChangesAssignee
    /// </summary>
    [DataContract]
    public partial class IssueChangeChangesAssignee :  IEquatable<IssueChangeChangesAssignee>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueChangeChangesAssignee" /> class.
        /// </summary>
        /// <param name="Old">Old.</param>
        /// <param name="_New">_New.</param>
        public IssueChangeChangesAssignee(string Old = default(string), string _New = default(string))
        {
            this.Old = Old;
            this._New = _New;
        }
        
        /// <summary>
        /// Gets or Sets Old
        /// </summary>
        [DataMember(Name="old", EmitDefaultValue=false)]
        public string Old { get; set; }
        /// <summary>
        /// Gets or Sets _New
        /// </summary>
        [DataMember(Name="new", EmitDefaultValue=false)]
        public string _New { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IssueChangeChangesAssignee {\n");
            sb.Append("  Old: ").Append(Old).Append("\n");
            sb.Append("  _New: ").Append(_New).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as IssueChangeChangesAssignee);
        }

        /// <summary>
        /// Returns true if IssueChangeChangesAssignee instances are equal
        /// </summary>
        /// <param name="other">Instance of IssueChangeChangesAssignee to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IssueChangeChangesAssignee other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Old == other.Old ||
                    this.Old != null &&
                    this.Old.Equals(other.Old)
                ) && 
                (
                    this._New == other._New ||
                    this._New != null &&
                    this._New.Equals(other._New)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Old != null)
                    hash = hash * 59 + this.Old.GetHashCode();
                if (this._New != null)
                    hash = hash * 59 + this._New.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
