/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Rest.Api;
using Itofinity.Bitbucket.Rest.Model;
using Itofinity.Bitbucket.Rest.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Rest.Test
{
    /// <summary>
    ///  Class for testing IssueChangeChanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueChangeChangesTests
    {
        // TODO uncomment below to declare an instance variable for IssueChangeChanges
        //private IssueChangeChanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueChangeChanges
            //instance = new IssueChangeChanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueChangeChanges
        /// </summary>
        [Test]
        public void IssueChangeChangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueChangeChanges
            //Assert.IsInstanceOfType<IssueChangeChanges> (instance, "variable 'instance' is a IssueChangeChanges");
        }

        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Test]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Milestone'
        /// </summary>
        [Test]
        public void MilestoneTest()
        {
            // TODO unit test for the property 'Milestone'
        }
        /// <summary>
        /// Test the property 'Component'
        /// </summary>
        [Test]
        public void ComponentTest()
        {
            // TODO unit test for the property 'Component'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Test]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
