/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Rest.Api;
using Itofinity.Bitbucket.Rest.Model;
using Itofinity.Bitbucket.Rest.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Rest.Test
{
    /// <summary>
    ///  Class for testing ProjectLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectLinksTests
    {
        // TODO uncomment below to declare an instance variable for ProjectLinks
        //private ProjectLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectLinks
            //instance = new ProjectLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectLinks
        /// </summary>
        [Test]
        public void ProjectLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProjectLinks
            //Assert.IsInstanceOfType<ProjectLinks> (instance, "variable 'instance' is a ProjectLinks");
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Test]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

    }

}
