/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Rest.Api;
using Itofinity.Bitbucket.Rest.Model;
using Itofinity.Bitbucket.Rest.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Rest.Test
{
    /// <summary>
    ///  Class for testing RepositoryLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RepositoryLinksTests
    {
        // TODO uncomment below to declare an instance variable for RepositoryLinks
        //private RepositoryLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RepositoryLinks
            //instance = new RepositoryLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepositoryLinks
        /// </summary>
        [Test]
        public void RepositoryLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RepositoryLinks
            //Assert.IsInstanceOfType<RepositoryLinks> (instance, "variable 'instance' is a RepositoryLinks");
        }

        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Test]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'Pullrequests'
        /// </summary>
        [Test]
        public void PullrequestsTest()
        {
            // TODO unit test for the property 'Pullrequests'
        }
        /// <summary>
        /// Test the property 'Commits'
        /// </summary>
        [Test]
        public void CommitsTest()
        {
            // TODO unit test for the property 'Commits'
        }
        /// <summary>
        /// Test the property 'Forks'
        /// </summary>
        [Test]
        public void ForksTest()
        {
            // TODO unit test for the property 'Forks'
        }
        /// <summary>
        /// Test the property 'Watchers'
        /// </summary>
        [Test]
        public void WatchersTest()
        {
            // TODO unit test for the property 'Watchers'
        }
        /// <summary>
        /// Test the property 'Downloads'
        /// </summary>
        [Test]
        public void DownloadsTest()
        {
            // TODO unit test for the property 'Downloads'
        }
        /// <summary>
        /// Test the property 'Clone'
        /// </summary>
        [Test]
        public void CloneTest()
        {
            // TODO unit test for the property 'Clone'
        }
        /// <summary>
        /// Test the property 'Hooks'
        /// </summary>
        [Test]
        public void HooksTest()
        {
            // TODO unit test for the property 'Hooks'
        }

    }

}
