/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Refit.Api;
using Itofinity.Bitbucket.Refit.Model;
using Itofinity.Bitbucket.Refit.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Refit.Test
{
    /// <summary>
    ///  Class for testing CommentLinksSelf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CommentLinksSelfTests
    {
        // TODO uncomment below to declare an instance variable for CommentLinksSelf
        //private CommentLinksSelf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommentLinksSelf
            //instance = new CommentLinksSelf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommentLinksSelf
        /// </summary>
        [Test]
        public void CommentLinksSelfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommentLinksSelf
            //Assert.IsInstanceOfType<CommentLinksSelf> (instance, "variable 'instance' is a CommentLinksSelf");
        }

        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
