/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Refit.Api;
using Itofinity.Bitbucket.Refit.Model;
using Itofinity.Bitbucket.Refit.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Refit.Test
{
    /// <summary>
    ///  Class for testing Pullrequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PullrequestTests
    {
        // TODO uncomment below to declare an instance variable for Pullrequest
        //private Pullrequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Pullrequest
            //instance = new Pullrequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Pullrequest
        /// </summary>
        [Test]
        public void PullrequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Pullrequest
            //Assert.IsInstanceOfType<Pullrequest> (instance, "variable 'instance' is a Pullrequest");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Rendered'
        /// </summary>
        [Test]
        public void RenderedTest()
        {
            // TODO unit test for the property 'Rendered'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'MergeCommit'
        /// </summary>
        [Test]
        public void MergeCommitTest()
        {
            // TODO unit test for the property 'MergeCommit'
        }
        /// <summary>
        /// Test the property 'CommentCount'
        /// </summary>
        [Test]
        public void CommentCountTest()
        {
            // TODO unit test for the property 'CommentCount'
        }
        /// <summary>
        /// Test the property 'TaskCount'
        /// </summary>
        [Test]
        public void TaskCountTest()
        {
            // TODO unit test for the property 'TaskCount'
        }
        /// <summary>
        /// Test the property 'CloseSourceBranch'
        /// </summary>
        [Test]
        public void CloseSourceBranchTest()
        {
            // TODO unit test for the property 'CloseSourceBranch'
        }
        /// <summary>
        /// Test the property 'ClosedBy'
        /// </summary>
        [Test]
        public void ClosedByTest()
        {
            // TODO unit test for the property 'ClosedBy'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Test]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }
        /// <summary>
        /// Test the property 'Reviewers'
        /// </summary>
        [Test]
        public void ReviewersTest()
        {
            // TODO unit test for the property 'Reviewers'
        }
        /// <summary>
        /// Test the property 'Participants'
        /// </summary>
        [Test]
        public void ParticipantsTest()
        {
            // TODO unit test for the property 'Participants'
        }

    }

}
