/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Bitbucket.Refit.Api;
using Itofinity.Bitbucket.Refit.Model;
using Itofinity.Bitbucket.Refit.Client;
using System.Reflection;

namespace Itofinity.Bitbucket.Refit.Test
{
    /// <summary>
    ///  Class for testing Treeentry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TreeentryTests
    {
        // TODO uncomment below to declare an instance variable for Treeentry
        //private Treeentry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Treeentry
            //instance = new Treeentry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Treeentry
        /// </summary>
        [Test]
        public void TreeentryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Treeentry
            //Assert.IsInstanceOfType<Treeentry> (instance, "variable 'instance' is a Treeentry");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Commit'
        /// </summary>
        [Test]
        public void CommitTest()
        {
            // TODO unit test for the property 'Commit'
        }

    }

}
