/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Bitbucket.Refit.Model
{
    /// <summary>
    /// PullrequestLinks
    /// </summary>
    [DataContract]
    public partial class PullrequestLinks :  IEquatable<PullrequestLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PullrequestLinks" /> class.
        /// </summary>
        /// <param name="Self">Self.</param>
        /// <param name="Html">Html.</param>
        /// <param name="Commits">Commits.</param>
        /// <param name="Approve">Approve.</param>
        /// <param name="Diff">Diff.</param>
        /// <param name="Comments">Comments.</param>
        /// <param name="Activity">Activity.</param>
        /// <param name="Merge">Merge.</param>
        /// <param name="Decline">Decline.</param>
        public PullrequestLinks(CommentLinksSelf Self = default(CommentLinksSelf), CommentLinksSelf Html = default(CommentLinksSelf), CommentLinksSelf Commits = default(CommentLinksSelf), CommentLinksSelf Approve = default(CommentLinksSelf), CommentLinksSelf Diff = default(CommentLinksSelf), CommentLinksSelf Comments = default(CommentLinksSelf), CommentLinksSelf Activity = default(CommentLinksSelf), CommentLinksSelf Merge = default(CommentLinksSelf), CommentLinksSelf Decline = default(CommentLinksSelf))
        {
            this.Self = Self;
            this.Html = Html;
            this.Commits = Commits;
            this.Approve = Approve;
            this.Diff = Diff;
            this.Comments = Comments;
            this.Activity = Activity;
            this.Merge = Merge;
            this.Decline = Decline;
        }
        
        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=false)]
        public CommentLinksSelf Self { get; set; }
        /// <summary>
        /// Gets or Sets Html
        /// </summary>
        [DataMember(Name="html", EmitDefaultValue=false)]
        public CommentLinksSelf Html { get; set; }
        /// <summary>
        /// Gets or Sets Commits
        /// </summary>
        [DataMember(Name="commits", EmitDefaultValue=false)]
        public CommentLinksSelf Commits { get; set; }
        /// <summary>
        /// Gets or Sets Approve
        /// </summary>
        [DataMember(Name="approve", EmitDefaultValue=false)]
        public CommentLinksSelf Approve { get; set; }
        /// <summary>
        /// Gets or Sets Diff
        /// </summary>
        [DataMember(Name="diff", EmitDefaultValue=false)]
        public CommentLinksSelf Diff { get; set; }
        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public CommentLinksSelf Comments { get; set; }
        /// <summary>
        /// Gets or Sets Activity
        /// </summary>
        [DataMember(Name="activity", EmitDefaultValue=false)]
        public CommentLinksSelf Activity { get; set; }
        /// <summary>
        /// Gets or Sets Merge
        /// </summary>
        [DataMember(Name="merge", EmitDefaultValue=false)]
        public CommentLinksSelf Merge { get; set; }
        /// <summary>
        /// Gets or Sets Decline
        /// </summary>
        [DataMember(Name="decline", EmitDefaultValue=false)]
        public CommentLinksSelf Decline { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PullrequestLinks {\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  Commits: ").Append(Commits).Append("\n");
            sb.Append("  Approve: ").Append(Approve).Append("\n");
            sb.Append("  Diff: ").Append(Diff).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  Activity: ").Append(Activity).Append("\n");
            sb.Append("  Merge: ").Append(Merge).Append("\n");
            sb.Append("  Decline: ").Append(Decline).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PullrequestLinks);
        }

        /// <summary>
        /// Returns true if PullrequestLinks instances are equal
        /// </summary>
        /// <param name="other">Instance of PullrequestLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PullrequestLinks other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Self == other.Self ||
                    this.Self != null &&
                    this.Self.Equals(other.Self)
                ) && 
                (
                    this.Html == other.Html ||
                    this.Html != null &&
                    this.Html.Equals(other.Html)
                ) && 
                (
                    this.Commits == other.Commits ||
                    this.Commits != null &&
                    this.Commits.Equals(other.Commits)
                ) && 
                (
                    this.Approve == other.Approve ||
                    this.Approve != null &&
                    this.Approve.Equals(other.Approve)
                ) && 
                (
                    this.Diff == other.Diff ||
                    this.Diff != null &&
                    this.Diff.Equals(other.Diff)
                ) && 
                (
                    this.Comments == other.Comments ||
                    this.Comments != null &&
                    this.Comments.Equals(other.Comments)
                ) && 
                (
                    this.Activity == other.Activity ||
                    this.Activity != null &&
                    this.Activity.Equals(other.Activity)
                ) && 
                (
                    this.Merge == other.Merge ||
                    this.Merge != null &&
                    this.Merge.Equals(other.Merge)
                ) && 
                (
                    this.Decline == other.Decline ||
                    this.Decline != null &&
                    this.Decline.Equals(other.Decline)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Self != null)
                    hash = hash * 59 + this.Self.GetHashCode();
                if (this.Html != null)
                    hash = hash * 59 + this.Html.GetHashCode();
                if (this.Commits != null)
                    hash = hash * 59 + this.Commits.GetHashCode();
                if (this.Approve != null)
                    hash = hash * 59 + this.Approve.GetHashCode();
                if (this.Diff != null)
                    hash = hash * 59 + this.Diff.GetHashCode();
                if (this.Comments != null)
                    hash = hash * 59 + this.Comments.GetHashCode();
                if (this.Activity != null)
                    hash = hash * 59 + this.Activity.GetHashCode();
                if (this.Merge != null)
                    hash = hash * 59 + this.Merge.GetHashCode();
                if (this.Decline != null)
                    hash = hash * 59 + this.Decline.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
