/* 
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using Refit;

using Itofinity.Bitbucket.Refit.Client;
using Itofinity.Bitbucket.Refit.Api;
using Itofinity.Bitbucket.Refit.Model;

namespace Itofinity.Bitbucket.Refit.Test
{
    /// <summary>
    ///  Class for testing DownloadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DownloadsApiTests
    {
        private string hostUrl = "";
        private string userAgent = "Itofinity.Bitbucket.Refit.Test.DownloadsApiTests";

        private IDownloadsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = RestService.For<IDownloadsApi>(hostUrl);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DownloadsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DownloadsApi
            //Assert.IsInstanceOfType(typeof(DownloadsApi), instance, "instance is a DownloadsApi");
        }

        
        /// <summary>
        /// Test RepositoriesUsernameRepoSlugDownloadsFilenameDelete
        /// </summary>
        [Test]
        public async void RepositoriesUsernameRepoSlugDownloadsFilenameDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string filename = null;
            //string repo_slug = null;
            //var response = await instance.RepositoriesUsernameRepoSlugDownloadsFilenameDelete(userAgent, username, filename, repo_slug);
            //Assert.IsInstanceOf<Error> (response, "response is Error");
        }
        
        /// <summary>
        /// Test RepositoriesUsernameRepoSlugDownloadsFilenameGet
        /// </summary>
        [Test]
        public async void RepositoriesUsernameRepoSlugDownloadsFilenameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string filename = null;
            //string repo_slug = null;
            //var response = await instance.RepositoriesUsernameRepoSlugDownloadsFilenameGet(userAgent, username, filename, repo_slug);
            //Assert.IsInstanceOf<Error> (response, "response is Error");
        }
        
        /// <summary>
        /// Test RepositoriesUsernameRepoSlugDownloadsGet
        /// </summary>
        [Test]
        public async void RepositoriesUsernameRepoSlugDownloadsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string repo_slug = null;
            //var response = await instance.RepositoriesUsernameRepoSlugDownloadsGet(userAgent, username, repo_slug);
            //Assert.IsInstanceOf<Error> (response, "response is Error");
        }
        
        /// <summary>
        /// Test RepositoriesUsernameRepoSlugDownloadsPost
        /// </summary>
        [Test]
        public async void RepositoriesUsernameRepoSlugDownloadsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string repo_slug = null;
            //var response = await instance.RepositoriesUsernameRepoSlugDownloadsPost(userAgent, username, repo_slug);
            //Assert.IsInstanceOf<Error> (response, "response is Error");
        }
        
    }

}
